const hex = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "A", "B", "C", "D", "E", "F"];

const myColor = document.querySelector(".color");
const myBtn = document.getElementById("btn");
const wrapper = document.querySelector(".wrapper");

myBtn.addEventListener("click", function () {
  // array holding only the generic hashtag
  let hexColor = "#";
  // loop six times to create six digitals to complete the hex colour
  for (let i = 0; i < 6; i++) {
    // six digits will be taken from the random hex values generated by the function below
    hexColor += hex[getRandomNumber()];
  }
  // this will set the colour of the background based on the random hex colour generated
  wrapper.style.backgroundColor = hexColor;
  // this will set the different hex colour values in the html file
  myColor.textContent = hexColor;
});

// This will pick random numbers from the length of the hex array.
function getRandomNumber() {
  return Math.floor(Math.random() * hex.length);
}
